### ISSUE TITLE
set start offset animation

### ISSUE THREAD

**Issue by pishguy** [qwert2603/circular_reveal_animation#3]
in this current library options i don't know how can i set optional start animation, for example when i click on floating action button begin of start animation is zero, how can i set for example Offset.zero to another offset?

**Comment by qwert2603** [comment]
Do you mean start size / radius of reveal animation? Parameter `minRadius` may help you.

**Comment by pishguy** [comment]
@qwert2603 minRadius show widget by default, my mean is not that, for example with `Tween` animation we can set begin and end animation to start from to end

**Comment by qwert2603** [comment]
If you need to start animation with some start offset, You can use `animationController.forward(from: 0.2);`. For this approach You need access to `AnimationController`, that rules animation.

If that doesn't solve Your issue, please give me the detailed explanation.

**Comment by pishguy** [comment]
@qwert2603 

how about `animationController.reverse();` and dialogs?

**Comment by qwert2603** [comment]
As far as I know, we can't get access to `AnimationController` that rules animation for `showGeneralDialog`. But You will get same result, if specify needed `minRadius` in `CircularRevealAnimation`.
