### ISSUE TITLE
Update LICENSE

### ISSUE THREAD

**Issue by iandis** [qwert2603/circular_reveal_animation#6]
Hi thank you for your awesome work! However I think you need to update the license to include the **year** and the **author name**. I need the copyright notice to be included in one of my repo [here](https://github.com/iandis/coin-live/blob/master/lib/core/helpers/screen_router.dart) since I use one of your works in it.

**Comment by qwert2603** [comment]
Hello! Thank you for positive feedback on my library! I've just updated year and author name in license, so it is in actual state now. Have a good day and best wishes with your project!
