### ISSUE TITLE
Use slider or swipe gesture to control reveal animation

### ISSUE THREAD

**Issue by jtkeyva** [qwert2603/circular_reveal_animation#8]
Is it possible to attach the reveal to a controller so that if you swipe or pull a slider it reveals? Like slide to the right to reveal and then slide to the left and it closes back up. Slide half way and it reveals half.
Thanks

**Comment by qwert2603** [comment]
Hi! Sorry for the late answer.
`CircularRevealAnimation` has parameter `animation` of type `Animation<double>`, and it's possible to use `AlwaysStoppedAnimation` with the required value to control the reveal state.
Also it's possible to use `AnimationController` and set it's value explicitly depending on the slider's value.

**Comment by jtkeyva** [comment]
thank you :)
